language: java
install:
  - gem install hiptest-publisher
script:
- mvn clean test
- hiptest-publisher -c hiptest-publisher.conf --test-run-id=235722 --without=actionwords --push="target/cucumber-reports/Cucumber.json"