language: java
install:
- gem install hiptest-publisher
addons:
  sonarcloud:
    organization: rodrigueaf-github
    token:
      secure: "*********"
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=b5059c43240c1ded5afb4e989ef8a47d0efd6e41
- hiptest-publisher -c hiptest-publisher.conf --test-run-id=235722 --without=actionwords
  --push="target/cucumber-reports/Cucumber.json"
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
jobs:
  include:
  - stage: deploy
    deploy:
      provider: heroku
      api_key:
      app: simplehiptestpoc
# generate by (travis encrypt SOMEVAR="f33cdd9004299072b49fe1a5a0ae44b2cfde88e3" --add)
env:
  global:
    secure: 
